version: '3.8'

volumes:
  database:

services:
  app:
    build:
      context: ../
      dockerfile: "$BUILD_DIR/Dockerfile"
      args:
        - APP_DIR=$APP_DIR
        - ROADRUNNER_MAX_REQUESTS=$ROADRUNNER_MAX_REQUESTS
        - ROADRUNNER_WATCH=$ROADRUNNER_WATCH
        - ROADRUNNER_WORKERS=$ROADRUNNER_WORKERS
        - BUILD_DIR=$BUILD_DIR
    image: $APP_IMAGE
    restart: unless-stopped
    container_name: $APP_CONTAINER_NAME
    env_file:
      - app.env
    environment:
      ROADRUNNER_MAX_REQUESTS: $ROADRUNNER_MAX_REQUESTS
      ROADRUNNER_WATCH: $ROADRUNNER_WATCH
      ROADRUNNER_WORKERS: $ROADRUNNER_WORKERS
    ports:
      - $APP_PORT:8080
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: $DB_CONTAINER_NAME
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - app.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
    volumes:
      - database:/var/lib/mysql
